import Head from "next/head";

const Meta = (props) => {
    return (
        <Head>
            <title>{props.title ? props.title : "emilsthoughts"}</title>
            <link rel="icon" href="/favicon.ico" />
            <meta name="description" content="Generated by create next app" />
            <meta name="keywords" content="Test" />
            <meta name="author" content="Emil Rädsch" />
            <meta charset="UTF-8" />
        </Head>
    );
};

export default Meta;
